# Generated by Django 3.1.1 on 2023-01-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
