# Generated by Django 3.1.1 on 2023-01-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_backofficelogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='backofficelogs',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
