# Generated by Django 3.1.1 on 2023-01-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_statistic_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telegram_username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
