# Generated by Django 3.1.1 on 2023-01-11 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_statistic_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 22, 36, 9, 341351)),
        ),
    ]
