# Generated by Django 3.1.1 on 2023-01-12 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20230111_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 5, 10, 4, 32, 565723)),
        ),
    ]
